//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Laboratory_7
{
    using System;
    using System.Collections.Generic;
    
    public partial class fact_work
    {
        public int work_id { get; set; }
        public int worker_id { get; set; }
        public int place_id { get; set; }
        public System.DateTime start_date { get; set; }
        public System.DateTime end_date { get; set; }
    
        public virtual add_work add_work { get; set; }
        public virtual place place { get; set; }
        public virtual worker worker { get; set; }
    }
}
