//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Football_Ticket
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ftEntities1 : DbContext
    {
        public ftEntities1()
            : base("name=ftEntities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<employer> employer { get; set; }
        public virtual DbSet<match> match { get; set; }
        public virtual DbSet<places> places { get; set; }
        public virtual DbSet<team> team { get; set; }
        public virtual DbSet<ticket> ticket { get; set; }
    }
}
