//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Football_Ticket
{
    using System;
    using System.Collections.Generic;
    
    public partial class places
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public places()
        {
            this.ticket = new HashSet<ticket>();
        }
    
        public int place_id { get; set; }
        public Nullable<int> match_id { get; set; }
        public int sector { get; set; }
        public int row { get; set; }
        public int num_place { get; set; }
        public string type { get; set; }
        public Nullable<bool> season_ticket { get; set; }
        public Nullable<float> price { get; set; }
    
        public virtual match match { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ticket> ticket { get; set; }
    }
}
